"use client";
import { useMemo, useState } from "react";
import type { MarketDataRecord } from "../../../lib/data-center/types";
import { validateMarketRecord } from "../../../lib/data-center/validation";
const empty: MarketDataRecord={city:"",district:"",neighborhood:"",propertyType:"Konut",periodDate:new Date().toISOString().slice(0,10),sourceName:"",sourceNote:"",listingCount:0,salePriceM2:0,rentPriceM2:0,annualChangePercent:0,confidenceScore:70,liquidityScore:50,infrastructureScore:50,transportScore:50,verificationStatus:"review"};
export default function DataManagementPanel({ onSave }: { onSave:(record:MarketDataRecord)=>Promise<void>|void }) {
  const [record,setRecord]=useState(empty); const [message,setMessage]=useState(""); const issues=useMemo(()=>validateMarketRecord(record),[record]);
  const field=(key:keyof MarketDataRecord,label:string,type="text")=><label style={{display:"grid",gap:5,fontSize:11,fontWeight:800,color:"#4f6c86"}}>{label}<input type={type} value={String(record[key]??"")} onChange={(e)=>setRecord({...record,[key]:type==="number"?Number(e.target.value):e.target.value})} style={{padding:10,border:"1px solid #cbd9e6",borderRadius:9}}/></label>;
  return <div style={{padding:16,border:"1px solid #d7e3f0",borderRadius:16,background:"#fff"}}><h3 style={{marginTop:0,color:"#153a65"}}>Yeni Gerçek Veri Kaydı</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:10}}>{field("city","İl")}{field("district","İlçe")}{field("neighborhood","Mahalle")}{field("propertyType","Gayrimenkul Türü")}{field("periodDate","Dönem","date")}{field("sourceName","Kaynak")}{field("listingCount","İlan Sayısı","number")}{field("salePriceM2","Satış m² (TL)","number")}{field("rentPriceM2","Kira m² (TL)","number")}{field("confidenceScore","Güven Puanı","number")}</div>{issues.length>0&&<p style={{color:"#b45309",fontSize:12}}>{issues[0].message}</p>}<button type="button" disabled={issues.length>0} onClick={async()=>{await onSave(record);setMessage("Kayıt kaydedildi.");setRecord(empty);}} style={{marginTop:12,padding:"11px 16px",border:0,borderRadius:10,background:"#0d6efd",color:"#fff",fontWeight:900,cursor:"pointer",opacity:issues.length?0.5:1}}>Kaydet</button>{message&&<span style={{marginLeft:10,fontSize:12,color:"#16794b"}}>{message}</span>}</div>;
}
